import Head from "next/head";
import React from "react";
import { useBuyCredits } from "~/hook/useBuyCredits";

const BuyCredits: React.FC = () => {
  const { buyCredits } = useBuyCredits();

  const offers: {
    name: string;
    images: number;
    price: number;
    description: string;
    plan: "starter" | "pro" | "elite";
    popular?: boolean;
  }[] = [
    {
      name: "Starter Plan",
      images: 20,
      price: 1.99,
      description: "Perfect for beginners to get started.",
      plan: "starter", // Literal type
    },
    {
      name: "Pro Plan",
      images: 50,
      price: 3.99,
      description: "Best for regular users who need more designs.",
      popular: true,
      plan: "pro", // Literal type
    },
    {
      name: "Elite Plan",
      images: 100,
      price: 6.99,
      description: "Ideal for power users and businesses.",
      plan: "elite", // Literal type
    },
  ];

  return (
    <>
        <Head>
        <title>Name Design AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mt-24 flex-col container mx-auto gap-4 px-8">
      <div className="container mx-auto px-4">
        <h1 className="text-4xl font-bold text-center mb-6">
          Buy Credits
        </h1>
        <p className="text-center text-gray-300 mb-10">
          Choose the perfect plan for your design needs.
        </p>
        <div className="grid md:grid-cols-3 gap-6">
          {offers.map((offer, index) => (
            <div
              key={index}
              className={`border rounded-lg p-6 shadow-sm bg-white ${
                offer.popular ? "border-blue-500" : "border-gray-300"
              }`}
            >
              {offer.popular && (
                <div className="bg-blue-500 text-white text-xs uppercase px-2 py-1 rounded-full inline-block mb-4">
                  Most Popular
                </div>
              )}
              <h2 className="text-2xl font-bold text-gray-800 mb-2">{offer.name}</h2>
              <p className="text-gray-600 mb-4">{offer.description}</p>
              <p className="text-4xl font-bold text-gray-800 mb-6">
                ${offer.price.toFixed(2)}
              </p>
              <p className="text-gray-600 mb-6">{offer.images} images included</p>
              <button
                className="w-full bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600 transition"
                onClick={() => {
                  void buyCredits(offer.plan); // Type-safe usage
                }}
              >
                Buy Now
              </button>
            </div>
          ))}
        </div>
      </div>
      </main>
    </>
  );
};

export default BuyCredits;
