import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Button } from "~/component/Button";
import { FormGroup } from "~/component/FormGroup";
import { api } from "~/utils/api";
import { Input } from "../component/Input";
import { stylesData } from "../data/stylesData"; // Updated import location

const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    name: "",
    basePrompt: "",
    numberofImages: "1",
  });

  const [error, setError] = useState("");
  const [imagesUrl, setImagesUrl] = useState<{ imageUrl: string }[]>([]);
  const [activeTab, setActiveTab] = useState<keyof typeof stylesData>("Modern");
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [popupImage, setPopupImage] = useState<string | null>(null); // State for the popup image

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data) {
      setImagesUrl(data);
    },
    onError(error) {
      console.log(error);
      setError(error.message);
    },
  });

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!form.name || !form.basePrompt) {
      setError("Please type your name and select a style.");
      return;
    }

    const finalPrompt = `${form.basePrompt.replace("Text", form.name)}`;

    generateIcon.mutate({
      prompt: finalPrompt,
      numberOfImages: parseInt(form.numberofImages),
    });
  };

  const updateForm = (key: string) => {
    return (e: React.ChangeEvent<HTMLInputElement>) => {
      setForm((prev) => ({
        ...prev,
        [key]: e.target.value,
      }));
    };
  };

  const handleImageSelect = (basePrompt: string, src: string) => {
    setSelectedImage(src);
    setForm((prev) => ({
      ...prev,
      basePrompt,
    }));
    setError("");
  };

  const handleDownload = async (imageUrl: string) => {
    console.log("Attempting to download:", imageUrl); // Debug the URL
    try {
      const response = await fetch(imageUrl, { mode: "cors" });
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const blob = await response.blob();
      const blobUrl = window.URL.createObjectURL(blob);

      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = "generated_image.png";
      link.click();

      window.URL.revokeObjectURL(blobUrl);
    } catch (error) {
      console.error("Error downloading the image:", error);
      // Fallback: Open the image in a new tab for manual download
      window.open(imageUrl, "_blank");
    }
  };

  const handleShare = async (imageUrl: string) => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: "Check out this generated image!",
          text: "I created this awesome image using the app.",
          url: imageUrl,
        });
        alert("Shared successfully!");
      } catch (error) {
        console.error("Error sharing the image:", error);
      }
    } else {
      alert("Web Share API is not supported in your browser.");
    }
  };

  const openPopup = (imageUrl: string) => {
    setPopupImage(imageUrl); // Open the popup
  };

  const closePopup = () => {
    setPopupImage(null); // Close the popup
  };

  return (
    <>
      <Head>
        <title>Name Design AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container m-auto mb-24 flex flex-col px-8 py-8 max-w-screen-md">
        <h1 className="text-6xl">Generate your design</h1>
        <p className="text-2xl">Type your name / text</p>
        <form className="flex flex-col gap-3" onSubmit={handleFormSubmit}>
          <h2 className="text-xl">1. Type your name</h2>
          <FormGroup className="mb-12">
            <label>Name</label>
            <Input
              required
              value={form.name}
              onChange={updateForm("name")}
              placeholder="Type your name here"
            />
          </FormGroup>

          <h2 className="text-xl">2. Pick your style</h2>
          <div className="mb-12">
            {/* Tabs */}
            <div className="flex border-b mb-4">
              {Object.keys(stylesData).map((style) => (
                <button
                  key={style}
                  type="button"
                  onClick={() => setActiveTab(style as keyof typeof stylesData)}
                  className={`px-4 py-2 ${
                    activeTab === style
                      ? "border-b-2 border-blue-500 text-blue-500"
                      : "text-gray-500"
                  }`}
                >
                  {style}
                </button>
              ))}
            </div>

            {/* Image Grid */}
            <div className="grid grid-cols-4 sm:grid-cols-4 md:grid-cols-6 gap-4 max-w-30">
              {stylesData[activeTab].map(({ src, basePrompt }, index) => (
                <div
                  key={index}
                  className={`rounded shadow-md hover:shadow-lg transition cursor-pointer ${
                    selectedImage === src ? "ring-4 ring-blue-500" : ""
                  }`}
                  onClick={() => handleImageSelect(basePrompt, src)}
                >
                  <img
                    src={src}
                    alt={basePrompt}
                    className="rounded w-30 h-30 min-w-20 min-h-20 object-cover mx-auto"
                  />
                </div>
              ))}
            </div>
          </div>

          <h2 className="text-xl">3. How many do you want?</h2>
          <FormGroup className="mb-12">
            <label>Number of images</label>
            <Input
              required
              inputMode="numeric"
              pattern="[1-9]|10"
              value={form.numberofImages}
              onChange={updateForm("numberofImages")}
            />
          </FormGroup>

          {error && (
            <div className="bg-red-500 text-white rounded p-8 text-xl">
              {error}
            </div>
          )}

          <Button
            isLoading={generateIcon.isLoading}
            disabled={generateIcon.isLoading}
          >
            Submit
          </Button>
        </form>

        {imagesUrl.length > 0 && (
          <>
            <h2 className="text-xl">Your images</h2>
            <section className="grid grid-cols-4 gap-4 mb-12">
              {imagesUrl.map(({ imageUrl }, index) => (
                <div key={index} className="relative rounded shadow-md hover:shadow-lg transition">
                  {/* Buttons at Top-Right */}
                  <div className="absolute top-2 right-2 flex gap-2">
                    {/* Fullscreen Button */}
                    <button
                      onClick={() => openPopup(imageUrl)}
                      className="bg-gray-800 text-white rounded-full p-1 hover:bg-gray-700 focus:outline-none"
                      title="View Fullscreen"
                    >
                      ⬜️
                    </button>

                    {/* Download Button */}
                    <button
                      onClick={() => {
                        handleDownload(imageUrl).catch((error) => {
                          console.error("Error downloading the image:", error);
                        });
                      }}
                      className="bg-gray-800 text-white rounded-full p-1 hover:bg-gray-700 focus:outline-none"
                      title="Download Image"
                    >
                      ⬇️
                    </button>

                    {/* Share Button */}
                    <button
                      onClick={() => {
                        handleShare(imageUrl).catch((error) => {
                          console.error("Error sharing the image:", error);
                        });
                      }}
                      className="bg-gray-800 text-white rounded-full p-1 hover:bg-gray-700 focus:outline-none"
                      title="Share Image"
                    >
                      🔗
                    </button>
                  </div>

                  {/* Generated Image */}
                  <Image
                    src={imageUrl}
                    alt="Generated output"
                    width={512}
                    height={512}
                    className="w-full rounded"
                  />
                </div>
              ))}
            </section>
          </>
        )}

        {/* Popup Modal */}
        {popupImage && (
          <div className="fixed inset-0 z-50 bg-black bg-opacity-75 flex items-center justify-center">
            <div className="relative">
              <button
                onClick={closePopup}
                className="absolute top-2 right-2 bg-gray-800 text-white rounded-full p-2 hover:bg-gray-700 focus:outline-none"
                title="Close"
              >
                ✖️
              </button>
              <img
                src={popupImage}
                alt="Fullscreen view"
                className="max-w-full max-h-screen rounded"
              />
            </div>
          </div>
        )}
      </main>
    </>
  );
};

export default GeneratePage;
