import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Button } from "~/component/Button";
import { FormGroup } from "~/component/FormGroup";
import { api } from "~/utils/api";
import { Input } from "../component/Input";

const colors = [
  "blue",
  "red",
  "pink",
  "green",
  "orange",
  "yellow",
  "white",
  "black",
];

const GeneratePage: NextPage = () => {
 
  const [form,setForm] = useState(
    {
      prompt: "",
      color: "",
    }
  );
  const [imageUrl,setImageUrl] = useState('')

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data){
      if(!data.imageBase64) return;
      setImageUrl(data.imageBase64)
    },
  })

  function handelFormSubmit(e: React.FormEvent){
    e.preventDefault();
    generateIcon.mutate(form)
    setForm((prev) => ({ ...prev, prompt: ""}));
  }

  function updateForm(key: string){
    return function (e: React.ChangeEvent<HTMLInputElement>){
      setForm(prev => ({...prev,
        [key]: e.target.value,}))
    }
  }
  
  return (
    <>
      <Head>
        <title>Name Design Ai</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mt-24 flex-col container mx-auto gap-4 px-8">
        <h1 className="text-6xl">Generate your desing</h1>
        <p className="text-2xl">type your name / text </p>
        <form className="flex flex-col gap-3" onSubmit={handelFormSubmit}>
          <h2 className="text-xl">
            1. Type your name
          </h2>
          <FormGroup className="mb-12">
            <label>Prompt</label>
            <Input 
              value={form.prompt}
              onChange={updateForm("prompt")}>
            </Input>
          </FormGroup>
          <h2 className="text-xl">
            2. Pick your style
          </h2>
          <FormGroup className="grid grid-cols-4 mb-12">
            {colors.map(color => 
              <label key={color} className="flex gap-2">
              <input 
                type="radio"
                name="color"
                checked={color === form.color}
                onChange={() => setForm((prev) => ({...prev, color}))}>
              </input>
              {color}
              </label>
            )}
            
          </FormGroup>
          <Button isLoading={generateIcon.isLoading}
          disabled={generateIcon.isLoading}>
            Submit
          </Button>
        </form>
        {imageUrl &&
        <>
        <h2 className="text-xl">
        2. Your images
      </h2>
      <section className="grid grid-cols-4 gap-4 mb-12">
      <Image 
          src= {imageUrl} 
          alt="an image of your generated prompt"
          width="100" height="100" className="w-full"
        />
      </section>
        
        </>
        }
        
      </main>
    </>
  );
};

export default GeneratePage;
