import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { PrimaryLinkButton } from "~/component/PrimaryLinkButton";

const HomePage: NextPage = () => {

  function HeroBanner() {
    return (
      <section className="mt-12 mb-24 grid grid-cols-1 gap-12 px-8 sm:mt-24 sm:grid-cols-2">
        <div className="flex flex-col gap-4">
          <h1 className="text-5xl">Create Stunning Name Images!</h1>
          <p className="text-2xl">
          Transform your name into art with Name Design AI! Create stunning, personalized designs perfect for social media, branding, or self-expression. Unleash your creativity today!
          </p>
          <PrimaryLinkButton href={"/generate"} className="self-start">Generate your image</PrimaryLinkButton>
        </div>
        <Image className="order-first sm:-order-none" src="/banner.png" alt="bunch of nice looking icons" width="400" height="300"
        />
      </section>
    );
  }

  return (
    <>
      <Head>
        <title>Name Design Ai</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center">
        <HeroBanner/>
      </main>
    </>
  );
};

export default HomePage;